packages:
  - "apps/web"
  - "apps/admin"
  - "packages/*"
allowBuilds:
  "@reown/appkit": true
  bigint-buffer: false
  bufferutil: false
  esbuild: true
  utf-8-validate: false
confirmModulesPurge: false
verifyDepsBeforeRun: false
